# Configure "golangci-lint" command. This file makes it behave the same for devs and CI.
# See https://golangci-lint.run/usage/configuration
linters:
  enable:
    # Defaults.
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Added.
    - gofumpt
    - bodyclose
    - nakedret
    - predeclared

linters-settings:
  nakedret:
    max-func-lines: 0
