# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Variables that are evaluated the same way by all pipelines.

variables:
  # Go1ESOfficial compile-time variable. Indicates that this is in the official
  # pipeline. For example, image usage may be restricted, and the artifacts may
  # be signed by a followup step, if this is the rolling build.
  #
  # Check for not ending in (unofficial), rather than ending in (official).
  # Existing official pipeline names doing signing are "stuck" with their old
  # names due to how signing authorization is checked, so not all pipelines that
  # are official have an "(official)" suffix.
  #
  # Note that the value is coerced when used as a bool because variables are
  # always strings. Not-defined evaluates as false and works fine in conditions.
  - ${{ if not(endsWith(variables['Build.DefinitionName'], '(unofficial)')) }}:
    - name: Go1ESOfficial
      value: 'true'

  # Don't include our own CI in telemetry data.
  - name: MS_GOTOOLCHAIN_TELEMETRY_ENABLED
    value: '0'
