# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Run fuzz tests internally on a schedule.

trigger: none
pr: none
schedules:
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml#cron-syntax
  - cron: '0 8 * * 1-5'
    displayName: Run fuzz tests once a day
    branches:
      include:
        - main
    always: true

resources:
  pipelines:
    - pipeline: build
      source: microsoft-go
      branch: microsoft/main
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: NetCore1ESPool-Internal
        image: 1es-windows-2022
        os: windows

    stages:
      - stage: Fuzz
        jobs:
          - template: /eng/pipelines/jobs/fuzz.yml@self
            parameters:
              name: Linux
              platform: linux-amd64
              pool:
                name: NetCore1ESPool-Internal
                image: 1es-ubuntu-2004
                os: linux

          - template: /eng/pipelines/jobs/fuzz.yml@self
            parameters:
              name: Linux_openssl
              platform: linux-amd64
              goExperiment: opensslcrypto
              pool:
                name: NetCore1ESPool-Internal
                image: 1es-ubuntu-2004
                os: linux

          - template: /eng/pipelines/jobs/fuzz.yml@self
            parameters:
              name: Windows_cng
              platform: windows-amd64
              goExperiment: cngcrypto
              pool:
                name: NetCore1ESPool-Internal
                image: 1es-windows-2022
                os: windows
