# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# For info about runtime parameters, see https://github.com/microsoft/go-infra/blob/main/docs/pipeline-yml-style.md#runtime-parameters
parameters:
  - name: releaseVersions
    displayName: >
      List of versions to release. Include Microsoft revision suffix (-1) and boring/FIPS suffix
      (-fips) if they apply. Write in YAML format: write one version number per line with '-' and a
      space at the beginning of each line.
    type: object

  - name: isSecurityRelease
    displayName: >
      This release includes security fixes:
    type: string
    default: Cancel
    values:
      - True
      - False
      - Cancel
    
  - name: notify
    displayName: >
      A GitHub username to @mention in the tracking issue to subscribe them to updates. Do not
      include '@' below. 'ghost' notifies nobody.
    type: string
    default: ghost

  # This parameter intentionally has no default: see release-go-pipeline.yml
  - name: goReleaseConfigVariableGroup
    displayName: '[Use "go-release-config" for a real release] Variable group that specifies release target locations and auth.'
    type: string

trigger: none
pr: none

variables:
  - group: Microsoft-GoLang-bot
  # Import config group. This may direct the build to use secrets from the other groups.
  - group: ${{ parameters.goReleaseConfigVariableGroup }}

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: NetCore1ESPool-Svc-Internal
        image: 1es-windows-2022
        os: windows
      suppression:
        suppressionFile: $(Build.SourcesDirectory)/.config/guardian/.gdnsuppress
      tsa:
        enabled: true
        configFile: $(Build.SourcesDirectory)/.config/tsa/tsaoptions.json

    stages:
      - stage: Release
        jobs:
          # Validation for complex inputs.
          - ${{ if not(in(parameters.isSecurityRelease, 'True', 'False')) }}:
            - 'Cancelled run. Please pick an option to indicate whether or not this is a security release.': error

          - template: /eng/pipelines/jobs/releasego.yml@self
            parameters:
              steps:
                - script: |
                    releasego create-release-day-issue \
                      -notify '${{ parameters.notify }}' \
                      -releases '${{ join(',', parameters.releaseVersions) }}' \
                      -repo '$(TargetGitHubRepo)' \
                      -github-app-id '$(BotAccount-bot-for-go-app-id)' \
                      -github-app-installation '$(BotAccount-bot-for-go-installation)' \
                      -github-app-private-key '$(BotAccount-bot-for-go-private-key)' \
                      -set-azdo-variable-name GO_RELEASE_DAY_ISSUE_NUMBER
                  displayName: Create release day tracking issue

                - template: ../steps/report.yml
                  parameters:
                    releaseIssue: $(GO_RELEASE_DAY_ISSUE_NUMBER)
                    reason: start
                    buildStatus: InProgress
                    start: true

                - ${{ each version in parameters.releaseVersions }}:
                  - script: |
                      releasego build-pipeline \
                        -id '$(GoReleaseBuildPipelineID)' \
                        -org 'https://dev.azure.com/dnceng/' \
                        -proj 'internal' \
                        -branch '$(Build.SourceBranch)' \
                        -commit '$(Build.SourceVersion)' \
                        -azdopat '$(System.AccessToken)' \
                        -set-azdo-variable GO_RELEASE_BUILDID \
                        p releaseVersion '${{ version }}' \
                        p releaseIssue '$(GO_RELEASE_DAY_ISSUE_NUMBER)' \
                        p goReleaseConfigVariableGroup '${{ parameters.goReleaseConfigVariableGroup }}'
                    displayName: (${{ version }}) 🚀 Start microsoft/go build preparation
                  - template: ../steps/report.yml
                    parameters:
                      releaseIssue: $(GO_RELEASE_DAY_ISSUE_NUMBER)
                      version: ${{ version }}
                      condition: succeeded()
                      buildPipeline: microsoft-go-infra-release-build
                      buildID: $(GO_RELEASE_BUILDID)
                      buildStatus: NotStarted
                      start: true
                      reason: queued build

                - script: |
                    releasego build-pipeline \
                      -id '$(GoReleaseImagesPipelineID)' \
                      -org 'https://dev.azure.com/dnceng/' \
                      -proj 'internal' \
                      -branch '$(Build.SourceBranch)' \
                      -commit '$(Build.SourceVersion)' \
                      -azdopat '$(System.AccessToken)' \
                      -set-azdo-variable GO_RELEASE_IMAGES_BUILDID \
                      p releaseVersions '${{ convertToJson(parameters.releaseVersions) }}' \
                      p notify '${{ parameters.notify }}' \
                      p isSecurityRelease '${{ parameters.isSecurityRelease }}' \
                      p releaseIssue '$(GO_RELEASE_DAY_ISSUE_NUMBER)' \
                      p goReleaseConfigVariableGroup '${{ parameters.goReleaseConfigVariableGroup }}'
                  displayName: 🚀 Start microsoft/go-images build
                - template: ../steps/report.yml
                  parameters:
                    releaseIssue: $(GO_RELEASE_DAY_ISSUE_NUMBER)
                    condition: succeeded()
                    buildPipeline: microsoft-go-infra-release-go-images
                    buildID: $(GO_RELEASE_IMAGES_BUILDID)
                    buildStatus: NotStarted
                    start: true
                    reason: queued build

                - template: ../steps/report.yml
                  parameters:
                    releaseIssue: $(GO_RELEASE_DAY_ISSUE_NUMBER)
                    reason: complete
