# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# This pipeline analyzes the repo with CodeQL.

trigger: none
pr: none
schedules:
  - cron: '0 16 * * Mon,Wed,Fri'
    displayName: Analyze
    branches:
      include:
        - main

variables:
  # Enable CodeQL scan and configure options.
  # https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/codeql/configuring-codeql3000-ado-pipelines#additional-options
  - name: Codeql.Enabled
    value: true
  - name: Codeql.Language
    value: go

jobs:
  - job: CodeQL
    workspace:
      clean: all
    pool:
      # This is a utility job: use generic recent LTS.
      name: NetCore1ESPool-Svc-Internal
      demands: ImageOverride -equals Build.Ubuntu.1804.Amd64
    steps:
      - template: steps/checkout-unix-task.yml
      - template: steps/init-go.yml

      - task: CodeQL3000Init@0

      - script: go build ./...
        displayName: Build

      - task: CodeQL3000Finalize@0
