# Copyright (c) Microsoft Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This pipeline runs rolling validation, like CodeQL.

trigger: none
pr: none
schedules:
  - cron: '45 11 * * 2'
    displayName: Weekly CodeQL
    branches:
      include:
        - main

# For info about runtime parameters, see https://github.com/microsoft/go-infra/blob/main/docs/pipeline-yml-style.md#runtime-parameters
parameters:
  - name: enableCodeQL
    displayName: '[Debug input] Enable CodeQL, ignoring cadence. Use to try modifications in dev branches.'
    type: boolean
    default: false
  - name: disableTSA
    displayName: '[Debug input] Disable TSA reporting. Use to try modifications in dev branches.'
    type: boolean
    default: false

variables:
  - name: Codeql.PublishDatabase
    value: true
  - name: Codeql.PublishDatabaseLog
    value: true
  - name: Codeql.PublishDatabaseLog
    value: true
  - ${{ if parameters.enableCodeQL }}:
    # The default cadence is ok for official branches. The cadence is per-branch.
    # For a dev build, the cadence would prevent dev iteration.
    # https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/codeql/codeql-general-faq#how-do-i-check-if-my-project-is-onboarded
    - name: Codeql.Cadence
      value: 0

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: NetCore1ESPool-Internal
      image: 1es-windows-2022
      os: windows
    sdl:
      codeql:
        enabledOnNonDefaultBranches: ${{ parameters.enableCodeQL }}
        language: go
      suppression:
        suppressionFile: $(Build.SourcesDirectory)/eng/compliance/.gdnsuppress
      tsa:
        enabled: ${{ not(parameters.disableTSA) }}
        configFile: $(Build.SourcesDirectory)/eng/compliance/tsaoptions.json

    stages:
      - stage: Analyze
        jobs:
          - job: Analyze
            workspace:
              clean: all
            steps:
              - task: GoTool@0
                inputs:
                  version: 1.22.1

              - script: |
                  go build ./...
                displayName: go
