# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

trigger: none
pr: none

resources:
  pipelines:
    - pipeline: build
      source: microsoft-go
      trigger:
        branches:
          include:
            # go-images doesn't currently have a place for updates from microsoft/main to go. This
            # should be addressed once the repo has a nightly branch:
            # https://github.com/microsoft/go/issues/169. Until then, don't trigger on
            # microsoft/main because those updates will always fail to generate.
            # - microsoft/main
            - microsoft/release-branch.*
            - microsoft/dev.boringcrypto.go*
            - dev/official/*

variables:
  - group: Microsoft-GoLang-bot

jobs:
  - job: Update
    workspace:
      clean: all
    pool:
      # This is a utility job: use generic recent LTS.
      vmImage: ubuntu-20.04
    variables:
      assetJsonPath: $(Pipeline.Workspace)/build/BuildAssets/assets.json
    steps:
      - template: steps/checkout-unix-task.yml
      - template: steps/init-pwsh-task.yml

      - pwsh: |
          echo "pipelineName: $(resources.pipeline.build.pipelineName)"
          echo "pipelineID: $(resources.pipeline.build.pipelineID)"
          echo "runName: $(resources.pipeline.build.runName)"
          echo "runID: $(resources.pipeline.build.runID)"
          echo "sourceBranch: $(resources.pipeline.build.sourceBranch)"
          echo "sourceCommit: $(resources.pipeline.build.sourceCommit)"
        displayName: Log source build/pipeline info

      - download: build
        artifact: BuildAssets

      - template: steps/init-go.yml
      - template: steps/set-bot-git-author.yml

      - pwsh: |
          go run ./cmd/dockerupdatepr `
            -origin https://microsoft-golang-bot:$(BotAccount-microsoft-golang-bot-PAT)@github.com/microsoft/go-images `
            -github-pat $(BotAccount-microsoft-golang-bot-PAT) `
            -github-pat-reviewer $(BotAccount-microsoft-golang-review-bot-PAT) `
            -build-asset-json "$(assetJsonPath)"
        displayName: Update go-images
