# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# https://dev.azure.com/dnceng/internal/_build?definitionId=1495

trigger: none
pr: none
schedules: []

variables:
  - group: Microsoft-GoLang-bot
  - group: DotNet-VSTS-Infra-Access
  - template: variables/pipeline.yml

extends:
  template: upstream-sync.yml
