# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# official: https://dev.azure.com/dnceng/internal/_build?definitionId=1061
# unofficial: https://dev.azure.com/dnceng/internal/_build?definitionId=1495

pipelineymlgen:
  output:
    - file: upstream-sync-pipeline-unofficial.yml
      data:
        official: false
    - file: upstream-sync-pipeline.yml
      data:
        official: true
---

parameters: []

trigger: none
pr: none
schedules:
  - ${ inlineif .official }:
    - cron: '0 16 * * Mon,Wed,Fri'
      displayName: Sync from upstream three times a week
      branches:
        include:
          - main
      always: true

variables:
  - group: Microsoft-GoLang-bot
  - group: DotNet-VSTS-Infra-Access
  - template: variables/pipeline.yml

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  ${ inlineif .official }:
    template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  ${ inlineelse }:
    template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: NetCore1ESPool-Internal
        image: 1es-windows-2022
        os: windows
      suppression:
        suppressionFile: $(Build.SourcesDirectory)/.config/guardian/.gdnsuppress
      tsa:
        enabled: true
        configFile: $(Build.SourcesDirectory)/.config/tsa/tsaoptions.json

    stages:
      - stage: Sync
        jobs:
          - job: Sync
            pool:
              name: NetCore1ESPool-Internal
              image: 1es-ubuntu-2004
              os: linux
            workspace:
              clean: all
            steps:
              - template: /eng/pipelines/steps/checkout-unix-task.yml@self

              - template: /eng/pipelines/steps/init-go.yml@self
              - template: /eng/pipelines/steps/set-bot-git-author.yml@self

              - pwsh: |
                  go run ./cmd/sync `
                    -git-auth api `
                    -github-user bot-for-go `
                    -github-app-client-id $(BotAccount-bot-for-go-client-id) `
                    -github-app-installation $(BotAccount-bot-for-go-installation) `
                    -github-app-private-key '$(BotAccount-bot-for-go-private-key)' `
                    -github-reviewer-app-client-id $(BotAccount-review-bot-for-go-client-id) `
                    -github-reviewer-app-installation $(BotAccount-review-bot-for-go-installation) `
                    -github-reviewer-app-private-key '$(BotAccount-review-bot-for-go-private-key)' `
                    -azdo-dnceng-pat $(dn-bot-dnceng-build-rw-code-rw)
                displayName: Sync
