// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package main

import (
	"os"
	"os/exec"
	"path/filepath"

	"github.com/microsoft/go-infra/executil"
)

const rebaseSummary = "Run 'git rebase -i' on the commits created by 'apply'."

const rebaseDescription = rebaseSummary + `

This command rebases the commits applied to the submodule based on patch files. It uses the HEAD
commit recorded by "apply" as the base commit.

You can use this command to apply fixup and squash commits generated by the "git commit" args
"--fixup" and "--squash". To do this, configure Git using "git config --global rebase.autoSquash 1"
before running this command.

Be aware that editing earlier patch files may cause conflicts with later patch files.
` + repoRootSearchDescription

var rebase = subcommand{
	Name:    "rebase",
	Summary: rebaseSummary,
	Handle: func() error {
		if err := parseFlagArgs(rebaseDescription); err != nil {
			return err
		}

		rootDir, err := findOuterRepoRoot()
		if err != nil {
			return err
		}

		goDir := filepath.Join(rootDir, "go")

		since, err := readStatusFile(getPrePatchStatusFilePath(rootDir))
		if err != nil {
			return err
		}

		cmd := exec.Command("git", "rebase", "-i", since)
		cmd.Stdin = os.Stdin
		cmd.Dir = goDir

		return executil.Run(cmd)
	},
}
