// Copyright (c) Microsoft Corporation.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"path"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"github.com/microsoft/go-infra/gitcmd"
	"go.yaml.in/yaml/v4"
)

func main() {
	log.SetPrefix("godependabot: ")
	log.SetFlags(0)

	if err := run(); err != nil {
		log.Printf("error: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	exitCodeFlag := flag.Bool("exit-code", false, "if set, do not write any updates; instead exit 1 (for use in CI)")

	flag.Usage = func() {
		fmt.Fprintf(flag.CommandLine.Output(), "Usage: %s [flags]\n", os.Args[0])
		flag.PrintDefaults()
		fmt.Fprintln(
			flag.CommandLine.Output(),
			"Update .github/dependabot.yml based on the contents of the current Git repository. "+
				"Adds an entry for every tracked Go module, and a github-actions entry when a CodeQL "+
				"workflow is present. Updates are grouped so they're bundled as much as possible, reducing PR volume.")
	}
	flag.Parse()

	dependabotPath := ".github/dependabot.yml"
	oldData, err := os.ReadFile(dependabotPath)
	if err != nil {
		return fmt.Errorf("read existing yml: %v", err)
	}
	oldData = bytes.ReplaceAll(oldData, []byte{'\r', '\n'}, []byte{'\n'})

	lines := strings.Split(string(oldData), "\n")

	const beginGeneratedComment = "  # Following lines generated by godependabot; DO NOT EDIT."
	const endGeneratedComment = "  # End of godependabot generated lines."

	// Trim trailing newlines to simplify logic. Note that newlines before the
	// generated comment are preserved.
	for len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) == "" {
		lines = lines[:len(lines)-1]
	}
	// Remove the previously generated block, delimited by the begin/end comments.
	// Fall back to removing just the begin comment for the legacy format that
	// predates the end marker.
	if start := slices.Index(lines, beginGeneratedComment); start != -1 {
		if rel := slices.Index(lines[start:], endGeneratedComment); rel != -1 {
			lines = slices.Delete(lines, start, start+rel+1)
		} else {
			lines = slices.Delete(lines, start, start+1)
		}
	}
	// Remove legacy single-line JSON entries (predates YAML output).
	lines = slices.DeleteFunc(lines, func(line string) bool {
		element, ok := strings.CutPrefix(line, "  - ")
		if !ok {
			return false
		}
		var entry dependabotEntry
		return json.Unmarshal([]byte(element), &entry) == nil
	})

	// Each generator inspects the repository and returns the dependabot entries
	// it's responsible for. Add new ecosystem logic by appending a generator.
	generators := []func(root string) ([]dependabotEntry, error){
		goModEntries,
		gitHubActionsEntries,
	}

	var entries []dependabotEntry
	for _, gen := range generators {
		genEntries, err := gen(".")
		if err != nil {
			return err
		}
		entries = append(entries, genEntries...)
	}
	slices.SortFunc(entries, func(a, b dependabotEntry) int {
		if c := strings.Compare(a.PackageEcosystem, b.PackageEcosystem); c != 0 {
			return c
		}
		return strings.Compare(a.Directory, b.Directory)
	})

	// Marshal the entries as a YAML sequence, then indent each line so the
	// sequence nests under the top-level "updates:" key.
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(entries); err != nil {
		return fmt.Errorf("marshal entries: %v", err)
	}
	if err := enc.Close(); err != nil {
		return fmt.Errorf("marshal entries: %v", err)
	}

	newLines := []string{beginGeneratedComment}
	for _, l := range strings.Split(strings.TrimRight(buf.String(), "\n"), "\n") {
		if l == "" {
			newLines = append(newLines, "")
			continue
		}
		line := "  " + l
		// Annotate the gh aw managed lines (the gh-aw-actions ignore and the
		// lock-file exclude-paths) so readers know they're compiler-locked.
		t := strings.TrimSpace(l)
		isGHAWManaged := strings.HasPrefix(t, "- ") && (strings.Contains(t, lockWorkflowGlob) || strings.Contains(t, ghawDependencyName))
		if isGHAWManaged {
			line += " " + ghawManagedComment
		}
		newLines = append(newLines, line)
	}
	newLines = append(newLines, endGeneratedComment, "")

	newData := []byte(strings.Join(append(lines, newLines...), "\n"))

	if bytes.Equal(oldData, newData) {
		// Up to date.
		log.Printf("%q already up to date.\n", dependabotPath)
		return nil
	}
	if *exitCodeFlag {
		return fmt.Errorf("%q is out of date", dependabotPath)
	}

	if err := os.WriteFile(dependabotPath, newData, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gendependabot: write: %v\n", err)
		os.Exit(2)
	}
	log.Printf("Updated %s.\n", dependabotPath)
	return nil
}

type dependabotEntry struct {
	PackageEcosystem string `json:"package-ecosystem" yaml:"package-ecosystem"`
	Directory        string `json:"directory" yaml:"directory"`
	Schedule         struct {
		Interval string `json:"interval" yaml:"interval"`
	} `json:"schedule" yaml:"schedule"`
	Groups                map[string]any   `json:"groups,omitempty" yaml:"groups,omitempty"`
	Ignore                []map[string]any `json:"ignore,omitempty" yaml:"ignore,omitempty"`
	ExcludePaths          []string         `json:"exclude-paths,omitempty" yaml:"exclude-paths,omitempty"`
	OpenPullRequestsLimit int              `json:"open-pull-requests-limit,omitempty" yaml:"open-pull-requests-limit,omitempty"`
}

// lockWorkflowGlob matches the gh aw managed workflow lock files that dependabot
// should not attempt to update directly.
const lockWorkflowGlob = ".github/workflows/*.lock.yml"

// ghawDependencyName is the dependabot dependency-name pattern for the actions
// pinned by 'gh aw compile'.
const ghawDependencyName = "github/gh-aw-actions*"

// ghawManagedComment explains why the gh aw managed lines must not be bumped by
// Dependabot. It's appended to both the ignore and exclude-paths lines.
const ghawManagedComment = "# Managed by gh aw compile. Version-locked to the gh-aw compiler; do not bump."

// goModEntries returns a dependabot entry for every Go module tracked in the
// repository, grouping each module's production dependencies together.
func goModEntries(root string) ([]dependabotEntry, error) {
	modules, err := findGoModuleDirs(root)
	if err != nil {
		return nil, fmt.Errorf("find modules: %v", err)
	}
	var entries []dependabotEntry
	for _, m := range modules {
		entry := dependabotEntry{
			PackageEcosystem: "gomod",
			Directory:        m,
			Groups: map[string]any{
				"all": map[string]any{
					"dependency-type": "production",
					"patterns":        []string{"*"},
				},
			},
		}
		entry.Schedule.Interval = "daily"
		entries = append(entries, entry)
	}
	return entries, nil
}

// gitHubActionsEntries returns a dependabot entry for GitHub Actions when the
// repository contains a CodeQL workflow and/or gh aw managed lock workflows.
// The CodeQL updates are grouped so they land in a single PR, and the gh aw
// managed lock files are excluded from direct updates.
func gitHubActionsEntries(root string) ([]dependabotEntry, error) {
	hasCodeQL, err := hasCodeQLWorkflow(root)
	if err != nil {
		return nil, fmt.Errorf("detect codeql workflow: %v", err)
	}
	hasLock, err := hasLockWorkflow(root)
	if err != nil {
		return nil, fmt.Errorf("detect gh aw lock workflow: %v", err)
	}
	if !hasCodeQL && !hasLock {
		return nil, nil
	}
	entry := dependabotEntry{
		PackageEcosystem:      "github-actions",
		Directory:             "/",
		OpenPullRequestsLimit: 10,
	}
	entry.Schedule.Interval = "daily"
	if hasCodeQL {
		entry.Groups = map[string]any{
			"codeql-action": map[string]any{
				"patterns": []string{"github/codeql-action/*"},
			},
		}
	}
	if hasLock {
		entry.Ignore = []map[string]any{
			{"dependency-name": ghawDependencyName},
		}
		entry.ExcludePaths = []string{lockWorkflowGlob}
	}
	return []dependabotEntry{entry}, nil
}

// gitTrackedFiles lists the files tracked in HEAD. Using 'git ls-tree' rather
// than a filesystem walk avoids problems with submodules and temporary data
// that's in .gitignore files.
func gitTrackedFiles(root string) ([]string, error) {
	out, err := gitcmd.CombinedOutput(
		root,
		"ls-tree",
		"--name-only",
		"-r",
		"-z", // null-terminate
		"HEAD",
	)
	if err != nil {
		return nil, err
	}
	var files []string
	for line := range strings.SplitSeq(out, "\x00") {
		if line == "" {
			continue
		}
		files = append(files, line)
	}
	return files, nil
}

func findGoModuleDirs(root string) ([]string, error) {
	files, err := gitTrackedFiles(root)
	if err != nil {
		return nil, err
	}
	var dirs []string
	for _, line := range files {
		// Normalize paths like "go.mod" and "foo/bar/go.mod" to what dependabot
		// expects: "/" and "foo/bar" respectively.
		line = "/" + line
		if pre, ok := strings.CutSuffix(line, "/go.mod"); ok {
			if pre == "" {
				pre = "/"
			}
			dirs = append(dirs, pre)
		}
	}
	sort.Strings(dirs)
	return dirs, nil
}

// hasCodeQLWorkflow reports whether any tracked GitHub Actions workflow
// references the github/codeql-action action.
func hasCodeQLWorkflow(root string) (bool, error) {
	files, err := gitTrackedFiles(root)
	if err != nil {
		return false, err
	}
	for _, f := range files {
		dir, name := path.Split(f)
		if dir != ".github/workflows/" {
			continue
		}
		if ext := path.Ext(name); ext != ".yml" && ext != ".yaml" {
			continue
		}
		data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(f)))
		if err != nil {
			return false, err
		}
		if bytes.Contains(data, []byte("github/codeql-action")) {
			return true, nil
		}
	}
	return false, nil
}

// hasLockWorkflow reports whether any tracked GitHub Actions workflow is a gh aw
// managed lock file (".github/workflows/*.lock.yml").
func hasLockWorkflow(root string) (bool, error) {
	files, err := gitTrackedFiles(root)
	if err != nil {
		return false, err
	}
	for _, f := range files {
		dir, name := path.Split(f)
		if dir != ".github/workflows/" {
			continue
		}
		if strings.HasSuffix(name, ".lock.yml") {
			return true, nil
		}
	}
	return false, nil
}
