// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"log"
	"os"
	"path"
	"path/filepath"
	"slices"
	"strings"

	"github.com/microsoft/go-infra/gitcmd"
	"go.yaml.in/yaml/v4"
)

func main() {
	log.SetPrefix("godependabot: ")
	log.SetFlags(0)

	if err := run(); err != nil {
		log.Printf("error: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	exitCodeFlag := flag.Bool("exit-code", false, "if set, do not write any updates; instead exit 1 (for use in CI)")

	flag.Usage = func() {
		fmt.Fprintf(flag.CommandLine.Output(), "Usage: %s [flags]\n", os.Args[0])
		flag.PrintDefaults()
		fmt.Fprintln(
			flag.CommandLine.Output(),
			"Update .github/dependabot.yml based on the contents of the current Git repository. "+
				"Adds an entry for every tracked Go module, and a github-actions entry when a CodeQL "+
				"workflow is present. Updates are grouped so they're bundled as much as possible, reducing PR volume.")
	}
	flag.Parse()

	dependabotPath := ".github/dependabot.yml"
	oldData, err := os.ReadFile(dependabotPath)
	if errors.Is(err, os.ErrNotExist) {
		// Seed a minimal dependabot config so the generated block has a top-level
		// "updates:" key to nest under. This lets the tool bootstrap the file in
		// repositories that don't have one yet.
		oldData = []byte(initialDependabotContent)
	} else if err != nil {
		return fmt.Errorf("read existing yml: %v", err)
	}
	oldData = bytes.ReplaceAll(oldData, []byte{'\r', '\n'}, []byte{'\n'})

	lines := strings.Split(string(oldData), "\n")

	// Use the full package path in the marker so it's easy to trace which tool
	// generated these lines when the file is checked into another repository.
	const beginGeneratedComment = "  # Following lines generated by github.com/microsoft/go-infra/cmd/godependabot; DO NOT EDIT."

	// Legacy begin markers from earlier versions of this tool (short name) and its
	// gomoddependabot predecessor. Keep matching them so files generated before
	// this change still get their stale block removed.
	const legacyBeginGeneratedComment = "  # Following lines generated by godependabot; DO NOT EDIT."
	const legacyGomodBeginGeneratedComment = "  # Following lines generated by gomoddependabot; DO NOT EDIT."

	// Trim trailing newlines to simplify logic. Note that newlines before the
	// generated comment are preserved.
	for len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) == "" {
		lines = lines[:len(lines)-1]
	}
	// Remove the previously generated block. Everything from the begin marker to
	// the end of the file is treated as generated, so trailing user content isn't
	// supported. Use the earliest begin marker in case multiple legacy markers are
	// present.
	beginMarkers := []string{
		beginGeneratedComment,
		legacyBeginGeneratedComment,
		legacyGomodBeginGeneratedComment,
	}
	start := -1
	for _, marker := range beginMarkers {
		if i := slices.Index(lines, marker); i != -1 && (start == -1 || i < start) {
			start = i
		}
	}
	if start != -1 {
		lines = lines[:start]
	}
	// Remove legacy single-line JSON entries (predates YAML output).
	lines = slices.DeleteFunc(lines, func(line string) bool {
		element, ok := strings.CutPrefix(line, "  - ")
		if !ok {
			return false
		}
		var entry dependabotEntry
		return json.Unmarshal([]byte(element), &entry) == nil
	})

	// List the files tracked in HEAD once and share the result with every
	// generator so we only shell out to Git a single time.
	files, err := gitTrackedFiles(".")
	if err != nil {
		return fmt.Errorf("list tracked files: %v", err)
	}

	// Each generator inspects the repository and appends the dependabot entries
	// it's responsible for. Add new ecosystem logic by appending a generator.
	generators := []func(entries []dependabotEntry, root string, files []string) ([]dependabotEntry, error){
		appendGoModEntries,
		appendGitHubActionsEntries,
	}

	var entries []dependabotEntry
	for _, gen := range generators {
		entries, err = gen(entries, ".", files)
		if err != nil {
			return err
		}
	}
	slices.SortFunc(entries, func(a, b dependabotEntry) int {
		if c := strings.Compare(a.PackageEcosystem, b.PackageEcosystem); c != 0 {
			return c
		}
		return strings.Compare(a.Directory, b.Directory)
	})

	// Marshal the entries as a YAML sequence, then indent each line so the
	// sequence nests under the top-level "updates:" key.
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(entries); err != nil {
		return fmt.Errorf("marshal entries: %v", err)
	}
	if err := enc.Close(); err != nil {
		return fmt.Errorf("marshal entries: %v", err)
	}

	newLines := []string{beginGeneratedComment}
	for _, l := range strings.Split(strings.TrimRight(buf.String(), "\n"), "\n") {
		if l == "" {
			newLines = append(newLines, "")
			continue
		}
		line := "  " + l
		// Annotate the gh aw managed lines (the gh-aw-actions ignore and the
		// lock-file exclude-paths) so readers know they're compiler-locked.
		t := strings.TrimSpace(l)
		isGHAWManaged := strings.HasPrefix(t, "- ") && (strings.Contains(t, lockWorkflowGlob) || strings.Contains(t, ghawDependencyName))
		if isGHAWManaged {
			line += " " + ghawManagedComment
		}
		newLines = append(newLines, line)
	}
	newLines = append(newLines, "")

	newData := []byte(strings.Join(append(lines, newLines...), "\n"))

	if bytes.Equal(oldData, newData) {
		// Up to date.
		log.Printf("%q already up to date.\n", dependabotPath)
		return nil
	}
	if *exitCodeFlag {
		return fmt.Errorf("%q is out of date", dependabotPath)
	}

	if err := os.MkdirAll(filepath.Dir(dependabotPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "godependabot: mkdir: %v\n", err)
		os.Exit(2)
	}
	if err := os.WriteFile(dependabotPath, newData, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "godependabot: write: %v\n", err)
		os.Exit(2)
	}
	log.Printf("Updated %s.\n", dependabotPath)
	return nil
}

type dependabotEntry struct {
	PackageEcosystem string `json:"package-ecosystem" yaml:"package-ecosystem"`
	Directory        string `json:"directory" yaml:"directory"`
	Schedule         struct {
		Interval string `json:"interval" yaml:"interval"`
	} `json:"schedule" yaml:"schedule"`
	Groups                map[string]any   `json:"groups,omitempty" yaml:"groups,omitempty"`
	Ignore                []map[string]any `json:"ignore,omitempty" yaml:"ignore,omitempty"`
	ExcludePaths          []string         `json:"exclude-paths,omitempty" yaml:"exclude-paths,omitempty"`
	OpenPullRequestsLimit int              `json:"open-pull-requests-limit,omitempty" yaml:"open-pull-requests-limit,omitempty"`
}

// initialDependabotContent is the minimal dependabot config used to bootstrap
// the file when the repository doesn't already have one. The generated block is
// appended under the top-level "updates:" key.
const initialDependabotContent = "version: 2\nupdates:\n"

// lockWorkflowGlob matches the gh aw managed workflow lock files that dependabot
// should not attempt to update directly.
const lockWorkflowGlob = ".github/workflows/*.lock.yml"

// ghawDependencyName is the dependabot dependency-name pattern for the actions
// pinned by 'gh aw compile'.
const ghawDependencyName = "github/gh-aw-actions*"

// ghawManagedComment explains why the gh aw managed lines must not be bumped by
// Dependabot. It's appended to both the ignore and exclude-paths lines.
const ghawManagedComment = "# Managed by gh aw compile. Version-locked to the gh-aw compiler; do not bump."

// copilotSetupStepsPath is the well-known location of the Copilot agentic
// workflow setup file that Dependabot should not attempt to update directly.
const copilotSetupStepsPath = ".github/workflows/copilot-setup-steps.yml"

// appendGoModEntries appends a dependabot entry for every Go module tracked in
// the repository, grouping each module's production dependencies together.
func appendGoModEntries(entries []dependabotEntry, root string, files []string) ([]dependabotEntry, error) {
	for _, m := range findGoModuleDirs(files) {
		entry := dependabotEntry{
			PackageEcosystem: "gomod",
			Directory:        m,
			Groups: map[string]any{
				"all": map[string]any{
					"patterns": []string{"*"},
				},
			},
		}
		entry.Schedule.Interval = "daily"
		entries = append(entries, entry)
	}
	return entries, nil
}

// appendGitHubActionsEntries appends a dependabot entry for GitHub Actions when
// the repository contains a CodeQL workflow and/or gh aw managed lock workflows.
// The CodeQL updates are grouped so they land in a single PR, and the gh aw
// managed lock files and the Copilot setup-steps file are excluded from direct
// updates.
func appendGitHubActionsEntries(entries []dependabotEntry, root string, files []string) ([]dependabotEntry, error) {
	hasCodeQL, err := hasCodeQLWorkflow(root, files)
	if err != nil {
		return entries, fmt.Errorf("detect codeql workflow: %v", err)
	}
	hasLock := hasLockWorkflow(files)
	hasCopilot := hasCopilotSetupStepsWorkflow(files)
	if !hasCodeQL && !hasLock && !hasCopilot {
		return entries, nil
	}
	entry := dependabotEntry{
		PackageEcosystem:      "github-actions",
		Directory:             "/",
		OpenPullRequestsLimit: 10,
	}
	entry.Schedule.Interval = "daily"
	if hasCodeQL {
		entry.Groups = map[string]any{
			"codeql-action": map[string]any{
				"patterns": []string{"github/codeql-action/*"},
			},
		}
	}
	if hasLock {
		entry.Ignore = []map[string]any{
			{"dependency-name": ghawDependencyName},
		}
		entry.ExcludePaths = []string{lockWorkflowGlob}
	}
	if hasCopilot {
		entry.ExcludePaths = append(entry.ExcludePaths, copilotSetupStepsPath)
	}
	return append(entries, entry), nil
}

// gitTrackedFiles lists the files tracked in HEAD. Using 'git ls-tree' rather
// than a filesystem walk avoids problems with submodules and temporary data
// that's in .gitignore files.
func gitTrackedFiles(root string) ([]string, error) {
	out, err := gitcmd.CombinedOutput(
		root,
		"ls-tree",
		"--name-only",
		"-r",
		"-z", // null-terminate
		"HEAD",
	)
	if err != nil {
		return nil, err
	}
	var files []string
	for line := range strings.SplitSeq(out, "\x00") {
		if line == "" {
			continue
		}
		files = append(files, line)
	}
	return files, nil
}

func findGoModuleDirs(files []string) []string {
	var dirs []string
	for _, line := range files {
		// Normalize paths like "go.mod" and "foo/bar/go.mod" to what dependabot
		// expects: "/" and "foo/bar" respectively.
		line = "/" + line
		if pre, ok := strings.CutSuffix(line, "/go.mod"); ok {
			if pre == "" {
				pre = "/"
			}
			dirs = append(dirs, pre)
		}
	}
	slices.Sort(dirs)
	return dirs
}

// hasCodeQLWorkflow reports whether any tracked GitHub Actions workflow
// references the github/codeql-action action.
func hasCodeQLWorkflow(root string, files []string) (bool, error) {
	for _, f := range files {
		dir, name := path.Split(f)
		if dir != ".github/workflows/" {
			continue
		}
		if ext := path.Ext(name); ext != ".yml" && ext != ".yaml" {
			continue
		}
		data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(f)))
		if err != nil {
			return false, err
		}
		if bytes.Contains(data, []byte("github/codeql-action")) {
			return true, nil
		}
	}
	return false, nil
}

// hasLockWorkflow reports whether any tracked GitHub Actions workflow is a gh aw
// managed lock file (".github/workflows/*.lock.yml").
func hasLockWorkflow(files []string) bool {
	for _, f := range files {
		dir, name := path.Split(f)
		if dir != ".github/workflows/" {
			continue
		}
		if strings.HasSuffix(name, ".lock.yml") {
			return true
		}
	}
	return false
}

// hasCopilotSetupStepsWorkflow reports whether the Copilot agentic workflow
// setup file (".github/workflows/copilot-setup-steps.yml") is tracked in the
// repository.
func hasCopilotSetupStepsWorkflow(files []string) bool {
	return slices.Contains(files, copilotSetupStepsPath)
}
