# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# This job sets up an agent to run release steps. Installs tools and releasego.
parameters:
  # The job ID/name.
  job: Release

  # By default, let the job overall continue 9 hours before failing. The job time has to account for
  # upstream availability, sync PR validation jobs, mirroring time, and internal build time. Each
  # waiting step should specify its own timeout that's just long enough for that particular step, so
  # we don't need to wait 8 hours to get notified about any particular step taking too long.
  timeoutInMinutes: 540

  # The microsoft/go release issue to post a success/failure report to, or 'nil'.
  releaseIssue: nil
  # A brief description of this job to include in the comment posted on GitHub (if enabled).
  reportDescription: release job.

  # Enables the UseDotNet task during the initialization steps. Used for release steps in the Arcade
  # toolset, which runs on .NET.
  useDotNet: false

  # Additional variables to include.
  variables: {}
  # The release steps to run.
  steps: []

jobs:
  - job: ${{ parameters.job }}
    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    workspace:
      clean: all
    pool:
      # This is a utility job: use generic recent LTS.
      name: NetCore1ESPool-Svc-Internal
      demands: ImageOverride -equals Build.Ubuntu.1804.Amd64
    variables:
      # Release steps may need to download build asset JSONs. Set up variables.
      assetsDir: $(Pipeline.Workspace)/BuildAssets
      buildAssetJsonFile: $(assetsDir)/assets.json
      artifactsDir: $(Pipeline.Workspace)/Artifacts

      # ID of the internal build pipeline. May need to be queued.
      microsoftGoInternalPipeline: 958

      ${{ insert }}: ${{ parameters.variables }}
    steps:
      - template: ../steps/fail-if-retry.yml

      - template: ../steps/checkout-unix-task.yml

      - template: ../steps/init-pwsh-task.yml
      - template: ../steps/init-go.yml
      - ${{ if eq(parameters.useDotNet, true) }}:
        - task: UseDotNet@2
          displayName: 'Use .NET SDK'
          inputs:
            version: 6.x

      - template: ../steps/set-bot-git-author.yml

      - script: |
          go install ./cmd/releasego
          echo "##vso[task.prependpath]$(go env GOPATH)/bin"
        displayName: Install releasego

      - script: releasego check-limits -pat '$(GitHubPAT)'
        displayName: Check GitHub rate limit

      - ${{ each step in parameters.steps }}:
        - ${{ step }}

      - script: releasego check-limits -pat '$(GitHubPAT)'
        displayName: Check GitHub rate limit

      - ${{ if ne(parameters.releaseIssue, 'nil') }}:
        - script: |
            releasego report \
              -i '${{ parameters.releaseIssue }}' \
              -m ':white_check_mark: Successfully ran ${{ parameters.reportDescription }}' \
              -repo '$(TargetGitHubRepo)' \
              -pat '$(GitHubPAT)'
          displayName: Report Success
          condition: succeeded()
        - script: |
            releasego report \
              -i '${{ parameters.releaseIssue }}' \
              -m ':rotating_light: Failed to run ${{ parameters.reportDescription }}.' \
              -repo '$(TargetGitHubRepo)' \
              -pat '$(GitHubPAT)'
          displayName: Report Failure
          condition: failed()
